return {
    name = "Quiver - Example Suite",
    info = "An example suite for Quiver.",
    entry = {
        file = "main",
        main = "main",
        step = "step",
        exit = "exit",
    },
    system = {
        model = true,
        texture = true,
        image = true,
        sound = true,
        music = true,
        font = true,
        shader = true,
    },
    window = {
        fullscreen = false,
        borderless = false,
        sync = true,
        msaa = true,
        resize = true,
        hidden = false,
        minimize = false,
        maximize = false,
        no_decor = false,
        no_focus = false,
        on_front = false,
        run_hidden = false,
        mouse_pass = false,
        draw_alpha = false,
        high_scale = false,
        name = "Quiver - Example Suite",
        rate = 144,
        shape = {1024, 768},
        alpha = 1.0
    }
}