[package]
name = "quiver"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib 	    = { version = "5.0.2" }
mlua   	    = { version = "0.10.1", features = ["luajit52", "vendored", "serialize", "async"] }
imgui       = { version = "0.12.0", features = ["tables-api"] }
serde  	    = { version = "1.0", features = ["derive"] }
serde_json  = { version = "1.0" }
rfd		    = { version = "0.15.1" }
copypasta   = { version = "0.8.2" }
parry3d     = { version = "0.17.1" }
parry2d     = { version = "0.17.1" }
rapier3d    = { version = "0.22.0", features = [ "parallel", "simd-stable", "serde-serialize" ] }
rapier2d    = { version = "0.22.0", features = [ "parallel", "simd-stable", "serde-serialize" ] }
notify      = { version = "6.1.1",  features = ["serde"] }
steamworks  = { version = "0.11.0", features = ["serde"] }
tokio   	= { version = "1.41.1", features = ["full"] }
reqwest 	= { version = "0.12", features = ["json"] }
discord-sdk = { version = "0.3.8" }

[build-dependencies]
bindgen = "0.70.1"
cc = "1.2.1"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"