[package]
name = "quiver"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib 	    = { version = "5.0.2" }
mlua   	    = { version = "0.10.1", features = ["luau-vector4", "vendored", "serialize"] }
serde  	    = { version = "1.0", features = ["derive"] }
serde_json  = { version = "1.0" }
parry3d     = { version = "0.17.1" }
parry2d     = { version = "0.17.1" }
rapier3d    = { version = "0.22.0", features = [ "parallel", "simd-stable", "serde-serialize" ] }
rapier2d    = { version = "0.22.0", features = [ "parallel", "simd-stable", "serde-serialize" ] }
imgui       = { version = "0.12.0", features = ["tables-api"] }
copypasta   = { version = "0.8.2" }
notify      = { version = "6.1.1" }
steamworks  = { version = "0.11.0", features = ["serde"] }

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"